name: Validate merge source
on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Error: Only develop branch can merge to main"
            exit 1
          fi
